### ISSUE TITLE
Impossible to install cityhash

### ISSUE THREAD

**Issue by frsqn** [deafdudecomputers/PalWorldSaveTools#16]
I cant install city hash on my computer even if i try to install it manually, so the fix_host_script cant start
![image](https://github.com/user-attachments/assets/542d6f08-82dc-42e8-bfc0-46a7ee6e1997)

**Comment by deafdudecomputers** [comment]
> I cant install city hash on my computer even if i try to install it manually, so the fix_host_script cant start ![image](https://private-user-images.githubusercontent.com/105961502/375019814-542d6f08-82dc-42e8-bfc0-46a7ee6e1997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTA4MzMsIm5iZiI6MTcyODQ5MDUzMywicGF0aCI6Ii8xMDU5NjE1MDIvMzc1MDE5ODE0LTU0MmQ2ZjA4LTgyZGMtNDJlOC1iZmMwLTQ2YTdlZTZlMTk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNjE1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWZhNWRhMGQxNWMyMGFjZjZmZGE2YTI1MDYwNzFjYzYxZGZhNjJmNGNmZjRmYjQ1MDM3MjIxZmM5ZWE4MTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G_OFa7321VeLvAo_3hKtMZloPIyLo34TRpluyExb0pI)

Please follow the README.md. 

Important Python Installation Note
Please make sure to use the official version of Python via python.org/downloads, NOT the WindowsApps version of Python. Otherwise, you may encounter issues due to downloading and installing packages. If you encounter any issues even after using the official version of Python, please install the Visual C++ Redistributable AIO from:
Visual C++ Redistributable AIO.

Installation Directions for AIO
Download VisualCppRedist_AIO_x86_x64.exe from the link above.
Run the downloaded file and follow the prompts to complete the installation.
After installation, use clean_up.cmd and try again.

**Comment by frsqn** [comment]
i did all of that...

**Comment by frsqn** [comment]
![image](https://github.com/user-attachments/assets/4802bb1b-e760-471d-b7f8-26a7f0b394a6)

**Comment by deafdudecomputers** [comment]
It has to do with your python or you didn't install the C++ AIO package. Both of them may be needed to use my tool. Cityhash needs both to work.

**Comment by frsqn** [comment]
i did everything right and cityhash doesnt want to get installed... Can u do it for me ? Do u have discord or something like that i send u everything :) It would be very nice for me and my friends

**Comment by frsqn** [comment]
![image](https://github.com/user-attachments/assets/00beec25-912c-4f63-993c-257fa205d952)
![image](https://github.com/user-attachments/assets/5788be90-a8e8-4f51-8e70-3c71db7e7553)
it worked but i had to install it myself with the vsbuildtools from microsoft
