### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Orengeorenge** [deafdudecomputers/PalWorldSaveTools#28]
Hi , I really appreciate that you are the only one who can do the update to the present.
I want to convert my server archiver to single-player archive.My NEW GUID is 00000000000000000000000000000001 and my OLD GUID is 9B642CB7000000000000000000000000.When I run the fix_host_save.cmd I input the both GUID but encounter some mistakes. 
Here is my files.https://github.com/Orengeorenge/Pal_file

**Comment by deafdudecomputers** [comment]
This error may be because you didn't have the save updated SINCE Feybreak released. My tools are updated to match the save structure. I'm currently waiting on server to update the save to match the tool's structure changes. And yep! That did the trick.
Good luck!
[LocalWorldSave_Updated.zip](https://github.com/user-attachments/files/18268763/LocalWorldSave_Updated.zip)

**Comment by Orengeorenge** [comment]
After I replace the 0001.sav and the Level.sav with the new and I ensure only the 0001.sav is in the Player folder, I entered the game but it showed the interface for creating a new character...so what should I do?

**Comment by deafdudecomputers** [comment]
![image](https://github.com/user-attachments/assets/10cefa45-fec0-42e2-966d-58d4b8cae5ac)
Looks fine to me.

Did you make sure to create new world, THEN quit and paste the updated saves in that new world?

**Comment by Orengeorenge** [comment]
I set up a new save for the game and I redid the whole process. So happy to see my pals back^^
Thank you for your help and for such a prompt response!
